# Generated by Django 5.0.7 on 2024-08-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
